// src/pages/user/User.vue
<script setup lang="ts">
import AppSidebar from '@/components/AppSidebar.vue'
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar'
import HeaderComponent from '@/components/HeaderComponent.vue'
</script>

<template>
  <SidebarProvider>
    <AppSidebar />
    <SidebarInset>
      <HeaderComponent />
      <div>
        <h1>User page</h1>
        <span>Essa é a pagina do usuario</span>
      </div>
    </SidebarInset>
  </SidebarProvider>
</template>

// src/routes/user.tsx
import { Outlet, createFileRoute } from '@tanstack/react-router'
import { AppSidebar } from '@/components/app-sidebar'
import Header from '@/components/header/Header'
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar'

export const Route = createFileRoute('/user')({
  component: RouteComponent,
})

function RouteComponent() {
  return (
    <SidebarProvider>
      <AppSidebar isAdmin={false} isSidebar={true} />
      <SidebarInset>
        <Header isAdminNav={false} />
        <Outlet /> 
      </SidebarInset>
    </SidebarProvider>
  )
}
