// src/components/HeaderComponent.vue
<script setup lang="ts">
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  
} from "@/components/ui/breadcrumb";
import { Separator } from "@/components/ui/separator";
import { SidebarTrigger } from "@/components/ui/sidebar";
</script>

<template>
  <header
    class="flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-[[data-collapsible=icon]]/sidebar-wrapper:h-12 bg-[#2f6ce4] border-l border-amber-950"
  >
    <div class="flex items-center gap-2 px-4">
      <SidebarTrigger class="-ml-1" />
      <Separator orientation="vertical" class="mr-2 h-4" />
      <Breadcrumb class="text-white">
            <BreadcrumbList>
              <BreadcrumbItem class="hidden md:block">
                <BreadcrumbLink href="#" class="text-white">
                  Controle de Estoque
                </BreadcrumbLink>
              </BreadcrumbItem>
              <span class="text-white hidden md:block">></span>
              <BreadcrumbItem>
                <BreadcrumbPage class="text-white">Data Fetching</BreadcrumbPage>
              </BreadcrumbItem>
            </BreadcrumbList>
          </Breadcrumb>
    </div>
  </header>
</template>

// src/components/header/Header.tsx
import { Separator } from '@radix-ui/react-separator'
import { SidebarTrigger } from '../ui/sidebar'
import {
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenuTrigger
} from '@/components/ui/navigation-menu'
import UserPhoto from '@/assets/user.png'
import Navigation from '@/components/header/navigation'

export default function Header({ isAdminNav = false }: { isAdminNav: boolean }) {
  return (
    <header className="p-4 flex  bg-blue-900 text-white items-center justify-between">
      <div className="lg:hidden flex items-center gap-2 px-4">
        <SidebarTrigger className="-ml-1" />
        <Separator
          orientation="vertical"
          className="mr-2 data-[orientation=vertical]:h-4"
        />
      </div>

      <Navigation isAdminNav={isAdminNav}/>

      <NavigationMenu>
        <NavigationMenuList>
          <NavigationMenuItem>
            <NavigationMenuTrigger>
              <img src={UserPhoto} alt="User Photo" className="w-[30px]" />
              <span className="ml-2">Admin</span>
            </NavigationMenuTrigger>
            <NavigationMenuContent>
              <NavigationMenuLink href='/'>Perfil</NavigationMenuLink>
              <NavigationMenuLink href="/docs">Deslogar</NavigationMenuLink>
            </NavigationMenuContent>
          </NavigationMenuItem>
        </NavigationMenuList>
      </NavigationMenu>
    </header>
  )
}
