// src/routes/admin.tsx
import { Outlet, createFileRoute } from '@tanstack/react-router'
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar'
import { AppSidebar } from '@/components/app-sidebar'
import Header from '@/components/header/Header'

export const Route = createFileRoute('/admin')({
  component: AdminLayout,
})

function AdminLayout() {
  return (
    <SidebarProvider>
      <AppSidebar isAdmin={true} isSidebar={true} />
      <SidebarInset>
        <Header isAdminNav={true} />
        <Outlet /> 
      </SidebarInset>
    </SidebarProvider>
  )
}

// src/pages/admin/Admin.vue
<script setup lang="ts">
import AppSidebar from '@/components/AppSidebar.vue'
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar'
import HeaderComponent from '@/components/HeaderComponent.vue'
</script>

<template>
  <SidebarProvider>
    <AppSidebar />
    <SidebarInset>
      <HeaderComponent />
      <div>
        <h1>Admin page</h1>
        <span>Essa é a pagina do admin</span>
      </div>
    </SidebarInset>
  </SidebarProvider>
</template>
